---
- name: Install broot
  macports:
    name: broot
    state: present
  become: true

- name: Create directories
  file:
    path: '{{ item }}'
    state: directory
  loop:
    - '{{ home }}/.config/broot/launcher/{{ ansible_user_shell | basename }}'
    - '{{ home }}/Library/Application Support/org.dystroy.broot/launcher/{{ ansible_user_shell | basename }}'

- name: Write config
  copy:
    src: conf.toml
    dest: '{{ home }}/.config/broot/conf.toml'
    backup: '{{ create_backups }}'

- name: Get broot launcher content
  command:
    cmd: 'broot --print-shell-function {{ ansible_user_shell | basename }}'
  register: _broot_launcher

- name: Write launcher script
  copy:
    content: '{{ _broot_launcher.stdout }}'
    dest: '{{ home }}/Library/Application Support/org.dystroy.broot/launcher/{{ ansible_user_shell | basename }}/1'

- name: Link launcher script
  file:
    src: '{{ home }}/Library/Application Support/org.dystroy.broot/launcher/{{ ansible_user_shell | basename }}/1'
    dest: '{{ home }}/.config/broot/launcher/{{ ansible_user_shell | basename }}/br'
    state: link

- name: Mark launcher as installed
  copy:
    content: |

      This file tells broot the installation of the br function was done.
      If there's a problem and you want to install it again run
          broot -- install
    dest: '{{ home }}/.config/broot/launcher/installed-v1'
