---
zsh_aliases:
  d: docker
  dc: docker-compose
  hm: home-manager
  k: kubectl
  la: ls -alh
  ll: ls -lh
  ls: ls -FG
  md: mkdir
  tree: tree -C
  v: nvim

zsh_plugin_directory: '{{ home }}/.local/share/zsh/plugins'
zsh_plugins:
  - repo: https://github.com/zsh-users/zsh-history-substring-search.git
    version: v1.0.2
    source_file: zsh-history-substring-search.zsh
  - repo: https://github.com/zsh-users/zsh-autosuggestions.git
    version: v0.6.4
    source_file: zsh-autosuggestions.zsh
  - repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    version: '0.7.1'
    source_file: zsh-syntax-highlighting.zsh
  - repo: https://github.com/hlissner/zsh-autopair.git
    version: v1.0
    source_file: autopair.zsh
  - repo: https://github.com/b4b4r07/enhancd.git
    version: v2.2.4
    source_file: init.sh
