add_newline = true

[aws]
disabled = true

[battery]
disabled = true

[character]
success_symbol = "[\\$](fg:green)"
error_symbol = "[\\$](fg:red)"

[cmd_duration]
format = "[| took $duration ]($style)"
style = "fg:cyan"

[conda]
disabled = true

[crystal]
disabled = true

[directory]
format = "[ $path ]($style)[$read_only]($read_only_style)"
style = "bg:bright-cyan fg:bright-white"

[docker_context]
disabled = true

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[env_var]
disabled = true

[erlang]
disabled = true

[git_branch]
format = "[ $symbol$branch ]($style)"
style = "bg:white fg:cyan"

[git_commit]
format = "[\\($hash\\)]($style)"
style = "bg:white fg:cyan"

[git_state]
format = "\\($state( $progress_current/$progress_total)]($style)\\)"
style = "bg:white fg:cyan"

[git_status]
format = "[(\\[$all_status$ahead_behind\\] )]($style)"
style = "bg:white fg:cyan"

[golang]
format = "[ $symbol$version ]($style)"
style = "fg:cyan"
symbol = " "

[hostname]
disabled = true

[java]
disabled = true

[jobs]
disabled = true

[julia]
disabled = true

[kubernetes]
disabled = false
format = "[ $symbol$context( \\($namespace\\)) ]($style)"
style = "bg:cyan fg:bright-white"
symbol = "ﴱ "

[memory_usage]
disabled = true

[hg_branch]
disabled = true

[nim]
disabled = true

[nix_shell]
disabled = true

[package]
disabled = true

[ocaml]
disabled = true

[php]
disabled = true

[python]
format = "[ ${symbol}${pyenv_prefix}${version}( \\($virtualenv\\)) ]($style)"
style = "fg:cyan"
symbol = " "

[ruby]
disabled = true

[rust]
format = "[ $symbol$version ]($style)"
style = "fg:cyan"
symbol = " "

[singularity]
disabled = true

[terraform]
format = "[ $symbol$workspace ]($style)"
style = "fg:cyan"
symbol = "TF "

[username]
disabled = true

[zig]
disabled = true

[purescript]
disabled = true
