---
- name: Check if Tower is installed
  stat:
    path: '{{ home }}/Library/Application Support/com.fournova.Tower3'
  register: _tower_installed

- name: Fail if Tower is not installed
  fail:
    msg: It seems Tower is not installed, please install it first.
  when: not _tower_installed.stat.exists

- name: Write environment.plist
  template:
    src: environment.plist.j2
    dest: '{{ home }}/Library/Application Support/com.fournova.Tower3/environment.plist'
    backup: '{{ create_backups }}'
