---
- name: Download MongoDB Shell archive
  ansible.builtin.get_url:
    url: 'https://downloads.mongodb.com/compass/mongosh-{{ mongodb_shell_version }}-darwin.zip'
    dest: '{{ home }}/.local/bin/mongosh-{{ mongodb_shell_version }}-darwin.zip'

- name: Unarchive
  ansible.builtin.unarchive:
    src: '{{ home }}/.local/bin/mongosh-{{ mongodb_shell_version }}-darwin.zip'
    dest: '{{ home }}/.local/bin'
    mode: u=rx,g=r,o=r

- name: Remove archive
  ansible.builtin.file:
    path: '{{ home }}/.local/bin/mongosh-{{ mongodb_shell_version }}-darwin.zip'
    state: absent
