---
- name: Install Starship
  macports:
    name: starship
    state: present

- name: Copy Starship configuration
  copy:
    src: './files/starship.toml'
    dest: '{{ home }}/.config/starship.toml'
    backup: '{{ create_backups }}'
